server {
    listen 80;
    server_name __DOMAIN__;

    location /static/ {
        alias __BASE_DIR__/project/static/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/__APP_NAME__.sock;
    }
}
